# Generated by Django 4.0 on 2022-04-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FolderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название папки')),
            ],
            options={
                'verbose_name': 'Название папки',
                'verbose_name_plural': 'Название папок',
            },
        ),
    ]
